server:
  port: 80
# 如果eureka端口号是8761 都不用配置网关直接能找到eureka
# 如果客户端发生变化，需要重启网关
# 没配置routes 用这个访问 http://localhost:80/aki-client-feign/hello-client?name=aaaa
# 80 这个是本网关设置的端口
# aki-client-feign 这个是路由过去的feign spring application name: aki-client-feign设置的名字
# hello-client?name=aaaa 这个是方法名 和 参数名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8769/eureka
spring:
  application:
    name: zuul-gateway		#Zuul网关在Eureka的服务名称，随便取


# 配置了routes用这个 http://localhost:80/tou/zidingyi/hello-client?name=aaaa
# 80 端口
# tou 是prefix
# zidingyi 是path
# hello-client?name=aaaa 方法
zuul:
  routes:
    zidingyi:
      service-id: aki-client-feign  # 需要路由过去的，client 微服务的名字
      path: /zidingyi/**
  ignored-services: '*'     # 表示禁用默认路由，只认我们自己配置的路由. 就是说上面那个路由就不行了
  prefix: /tou
