server:
  port: 9000
spring:
  application:
    name: zuul-gateway		#Zuul网关在Eureka的服务名称，随便取
    #http://localhost:9000/client-feign/hello-client?name=aaaa 用这个访问
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    zidingyi:
      service-id: client-feign
      path: /zidingyi/**
      #http://localhost:9000/zidingyi/hello-client?name=aaaa 配置了routes用这个
  ignored-services: '*' #用为服务的名称就访问不了了
  prefix: /tou  #加一个统一的头 http://localhost:9000/tou/zidingyi/hello-client?name=aaaa