server:
  port: 8763  #服务的端口号 如果启动好几个服务集群，要修改成不同的
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/  #注册中心的地址
  #spring cloud：服务注册时，设置使用ip注册，而不是主机名
  instance:
    preferIpAddress: true

spring:
  application:
    name: service-name  #服务名
